<?php

use Illuminate\Database\Seeder;

class BookingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bookings')->delete();
        
        \DB::table('bookings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'customer_id' => 2,
                'event_id' => 3,
                'quantity' => 1,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:03:21',
                'updated_at' => '2019-10-05 06:03:21',
                'event_title' => 'Global Marketing Conference',
                'event_start_date' => '2020-10-01',
                'event_end_date' => '2020-12-31',
                'event_start_time' => '14:00:00',
                'event_end_time' => '16:30:00',
                'event_category' => 'Business & Seminars',
                'order_number' => 1570255401753,
                'customer_name' => 'David lane',
                'customer_email' => 'davidlane@mail.com',
            ),
            1 => 
            array (
                'id' => 2,
                'customer_id' => 3,
                'event_id' => 3,
                'quantity' => 2,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:03:34',
                'updated_at' => '2019-10-05 06:03:34',
                'event_title' => 'Global Marketing Conference',
                'event_start_date' => '2020-10-01',
                'event_end_date' => '2020-12-31',
                'event_start_time' => '14:00:00',
                'event_end_time' => '16:30:00',
                'event_category' => 'Business & Seminars',
                'order_number' => 1570255414339,
                'customer_name' => 'Cora Woods',
                'customer_email' => 'corawoods@mail.com',
            ),
            2 => 
            array (
                'id' => 3,
                'customer_id' => 4,
                'event_id' => 3,
                'quantity' => 1,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:03:43',
                'updated_at' => '2019-10-05 06:03:43',
                'event_title' => 'Global Marketing Conference',
                'event_start_date' => '2020-10-01',
                'event_end_date' => '2020-12-31',
                'event_start_time' => '14:00:00',
                'event_end_time' => '16:30:00',
                'event_category' => 'Business & Seminars',
                'order_number' => 1570255423653,
                'customer_name' => 'Roman Pane',
                'customer_email' => 'romanpane@mail.com',
            ),
            3 => 
            array (
                'id' => 4,
                'customer_id' => 4,
                'event_id' => 3,
                'quantity' => 2,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:03:56',
                'updated_at' => '2019-10-05 06:03:56',
                'event_title' => 'Global Marketing Conference',
                'event_start_date' => '2020-10-01',
                'event_end_date' => '2020-12-31',
                'event_start_time' => '14:00:00',
                'event_end_time' => '16:30:00',
                'event_category' => 'Business & Seminars',
                'order_number' => 157025543694,
                'customer_name' => 'Roman Pane',
                'customer_email' => 'romanpane@mail.com',
            ),
            4 => 
            array (
                'id' => 5,
                'customer_id' => 5,
                'event_id' => 3,
                'quantity' => 1,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:04:05',
                'updated_at' => '2019-10-05 06:04:05',
                'event_title' => 'Global Marketing Conference',
                'event_start_date' => '2020-10-01',
                'event_end_date' => '2020-12-31',
                'event_start_time' => '14:00:00',
                'event_end_time' => '16:30:00',
                'event_category' => 'Business & Seminars',
                'order_number' => 1570255445284,
                'customer_name' => 'Tara Young',
                'customer_email' => 'tarayoung@mail.com',
            ),
            5 => 
            array (
                'id' => 6,
                'customer_id' => 2,
                'event_id' => 2,
                'quantity' => 1,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:04:22',
                'updated_at' => '2019-10-05 06:04:22',
                'event_title' => 'VR assistant Workshop',
                'event_start_date' => '2020-11-01',
                'event_end_date' => '2020-11-11',
                'event_start_time' => '09:00:00',
                'event_end_time' => '11:45:00',
                'event_category' => 'Business & Seminars',
                'order_number' => 1570255462705,
                'customer_name' => 'David lane',
                'customer_email' => 'davidlane@mail.com',
            ),
            6 => 
            array (
                'id' => 7,
                'customer_id' => 3,
                'event_id' => 6,
                'quantity' => 1,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:04:31',
                'updated_at' => '2019-10-05 06:04:31',
                'event_title' => 'Caribbean Karaoke Nights',
                'event_start_date' => '2020-10-01',
                'event_end_date' => '2020-12-31',
                'event_start_time' => '20:00:00',
                'event_end_time' => '23:00:00',
                'event_category' => 'Music & Concerts',
                'order_number' => 1570255471404,
                'customer_name' => 'Cora Woods',
                'customer_email' => 'corawoods@mail.com',
            ),
            7 => 
            array (
                'id' => 8,
                'customer_id' => 4,
                'event_id' => 5,
                'quantity' => 1,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:04:39',
                'updated_at' => '2019-10-05 06:04:39',
                'event_title' => 'Winter Wine Night',
                'event_start_date' => '2020-11-01',
                'event_end_date' => '2020-12-31',
                'event_start_time' => '20:00:00',
                'event_end_time' => '22:50:00',
                'event_category' => 'Food & Drink',
                'order_number' => 1570255479854,
                'customer_name' => 'Roman Pane',
                'customer_email' => 'romanpane@mail.com',
            ),
            8 => 
            array (
                'id' => 9,
                'customer_id' => 5,
                'event_id' => 1,
                'quantity' => 1,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:04:48',
                'updated_at' => '2019-10-05 06:04:48',
                'event_title' => 'Digital Marketing Seminar',
                'event_start_date' => '2020-11-25',
                'event_end_date' => '2020-11-25',
                'event_start_time' => '08:00:00',
                'event_end_time' => '10:30:00',
                'event_category' => 'Business & Seminars',
                'order_number' => 1570255488300,
                'customer_name' => 'Tara Young',
                'customer_email' => 'tarayoung@mail.com',
            ),
            9 => 
            array (
                'id' => 10,
                'customer_id' => 3,
                'event_id' => 7,
                'quantity' => 2,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:05:01',
                'updated_at' => '2019-10-05 06:05:01',
                'event_title' => 'Expresso Food Fare',
                'event_start_date' => '2020-11-26',
                'event_end_date' => '2020-11-29',
                'event_start_time' => '18:30:00',
                'event_end_time' => '22:00:00',
                'event_category' => 'Food & Drink',
                'order_number' => 1570255501287,
                'customer_name' => 'Cora Woods',
                'customer_email' => 'corawoods@mail.com',
            ),
            10 => 
            array (
                'id' => 11,
                'customer_id' => 4,
                'event_id' => 4,
                'quantity' => 2,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:05:10',
                'updated_at' => '2019-10-05 06:05:10',
                'event_title' => 'Seven Rocks Show',
                'event_start_date' => '2020-12-27',
                'event_end_date' => '2020-12-27',
                'event_start_time' => '18:00:00',
                'event_end_time' => '22:00:00',
                'event_category' => 'Music & Concerts',
                'order_number' => 157025551029,
                'customer_name' => 'Roman Pane',
                'customer_email' => 'romanpane@mail.com',
            ),
            11 => 
            array (
                'id' => 12,
                'customer_id' => 2,
                'event_id' => 7,
                'quantity' => 2,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:11:09',
                'updated_at' => '2019-10-05 06:11:09',
                'event_title' => 'Expresso Food Fare',
                'event_start_date' => '2020-11-26',
                'event_end_date' => '2020-11-29',
                'event_start_time' => '18:30:00',
                'event_end_time' => '22:00:00',
                'event_category' => 'Food & Drink',
                'order_number' => 1570255869788,
                'customer_name' => 'David lane',
                'customer_email' => 'davidlane@mail.com',
            ),
            12 => 
            array (
                'id' => 13,
                'customer_id' => 2,
                'event_id' => 4,
                'quantity' => 1,
                'price' => '0.00',
                'net_price' => '0.00',
                'status' => 1,
                'created_at' => '2019-10-05 06:11:33',
                'updated_at' => '2019-10-05 06:11:33',
                'event_title' => 'Seven Rocks Show',
                'event_start_date' => '2020-12-27',
                'event_end_date' => '2020-12-27',
                'event_start_time' => '18:00:00',
                'event_end_time' => '22:00:00',
                'event_category' => 'Music & Concerts',
                'order_number' => 1570255893618,
                'customer_name' => 'David lane',
                'customer_email' => 'davidlane@mail.com',
            ),
        ));
        
        
    }
}